server:
  maxHttpHeaderSize: 8KB
  tomcat:
    maxHttpFormPostSize: 2MB
    maxSwallowSize: 2MB
    maxConnections: 2000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 读库和写库的地址，目前写库可以配置为一个，读库可配置为多个
    url: jdbc:mysql://10.1.1.213:3306/edukg?useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf8
    username: root
    password: mysql@keg202
  data:
    neo4j:
      uri: bolt://10.1.1.213:7687
      username: neo4j
      password: neo4j@keg202
  redis:
    database: 0
    password:
    timeout: 600ms
    prefix: edukg:backend
    opengate: 1
    cluster:
      max-redirects: 2
      nodes:
        - 10.1.1.213:7001
        - 10.1.1.213:7002
        - 10.1.1.213:7003
        - 10.1.1.213:7004
        - 10.1.1.213:7005
        - 10.1.1.213:7006
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: 200ms
  es:
    address: 47.94.201.245
    port: 9200
    scheme: http
    username: elastic
    password: 5Vc8fC8kjJNiT=SYZFKF
    index:
      examSource: examsource
      irqa: irqa
      textBook: textbook
asyn:
  schedule:
    corePoolSize: 10
    maxPoolSize: 100
    queueCapacity: 10
    keepAliveSeconds: 60
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.tsinghua.edukg.dao.entity


address:
  server:
    qa: http://10.1.1.213:9719/
    linking: http://47.94.201.245:8000/
    sourcePath: http://47.94.201.245:8081
  file:
    examSource: /data/Gaokao/json
    jiebaDictLinux: /data/Gaokao/jieba/dicts/%s.txt
    textbook: /data/textbook/%s/OEBPS
    jiebaDictWin: C:\\Users\\feifei\\Desktop\\Gaokao\\jieba\\dicts\\%s.txt
    stopWords: static/stopWords.out
    sourcePath: /data1/home/keg
    subjectGraph: C:\\qatest\\subjectGraph\\%s.json
  sign:
    split: /

