server:
  maxHttpHeaderSize: 8KB
  tomcat:
    maxHttpFormPostSize: 2MB
    maxSwallowSize: 2MB
    maxConnections: 2000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 读库和写库的地址，目前写库可以配置为一个，读库可配置为多个
    url: jdbc:mysql://47.94.201.245:3306/edukg?useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf8
    username: root
    password: Keg2022!
    druid:
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initialSize: 1
      # 最小连接池数量
      minIdle: 1
      # 最大连接池数量
      maxActive: 10
      # 配置获取连接等待超时的时间
      maxWait: 10000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 验证连接有效与否的SQL，不同的数据配置不同
      validationQuery: select 1
      # 建议配置为true，不影响性能，并且保证安全性。
      # 申请连接的时候检测，如果空闲时间大于
      # timeBetweenEvictionRunsMillis，
      # 执行validationQuery检测连接是否有效。
      testWhileIdle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      # 这里建议配置为TRUE，防止取到的连接不可用
      testOnBorrow: true
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      # 是否缓存preparedStatement，也就是PSCache。
      # PSCache对支持游标的数据库性能提升巨大，比如说oracle。
      # 在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
      # 作者在5.5版本中使用PSCache，通过监控界面发现PSCache有缓存命中率记录，
      # 该应该是支持PSCache。
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 属性类型是字符串，通过别名的方式配置扩展插件，
      # 常用的插件有：
      # 监控统计用的filter:stat
      # 日志用的filter:log4j
      # 防御sql注入的filter:wall
      filters: stat
  data:
    neo4j:
      domain1:
        uri: bolt://47.94.201.245:7687
        username: neo4j
        password: neo4j@keg202
      domain2:
        uri: bolt://47.94.201.245:27687
        username: neo4j
        password: kegneo4j
  redis:
    database: 0
    password:
    timeout: 600ms
    prefix: edukg:backend
    opengate: 0
    cluster:
      max-redirects: 2
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: 200ms
  es:
    address: 47.94.201.245
    port: 9200
    scheme: http
    username: elastic
    password: 5Vc8fC8kjJNiT=SYZFKF
    index:
      examSource: examsource
      irqa: irqa
      textBook: new_book

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.tsinghua.edukg.dao.entity
asyn:
  schedule:
    corePoolSize: 10
    maxPoolSize: 100
    queueCapacity: 10
    keepAliveSeconds: 60

address:
  server:
    qa: http://47.94.201.245:9719/
    linking: http://47.94.201.245:8000/
    sourcePath: http://47.94.201.245:8081
  file:
    examSource: /data/Gaokao/json
    jiebaDictLinux: /data1/jieba/dicts/%s.txt
    textbook: /data/textbook/%s/OEBPS
    jiebaDictWin: C:\\Users\\feifei\\Desktop\\Gaokao\\jieba\\dicts\\%s.txt
    stopWords: static/stopWords.out
    sourcePath: /data1/home/keg
    subjectGraph: /data/subjectGraph/%s.json
  sign:
    split: /

