server:
  maxHttpHeaderSize: 8KB
  tomcat:
    maxHttpFormPostSize: 2MB
    maxSwallowSize: 2MB
    maxConnections: 2000
spring:
  data:
    neo4j:
      uri: bolt://10.1.1.213:7687
      username: neo4j
      password: neo4j@keg202
  redis:
    database: 0
    password:
    timeout: 600ms
    prefix: edukg:backend
    opengate: 1
    cluster:
      max-redirects: 2
      nodes:
        - 10.1.1.213:7001
        - 10.1.1.213:7002
        - 10.1.1.213:7003
        - 10.1.1.213:7004
        - 10.1.1.213:7005
        - 10.1.1.213:7006
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: 200ms
asyn:
  schedule:
    corePoolSize: 10
    maxPoolSize: 100
    queueCapacity: 10
    keepAliveSeconds: 60

address:
  server:
    qa: http://10.1.1.213:9719/
    linking: http://47.94.201.245:8000/
  file:
    examSource: /data/Gaokao/json
    jiebaDictLinux: /data/Gaokao/jieba/dicts/%s.txt
    jiebaDictWin: C:\\Users\\feifei\\Desktop\\Gaokao\\jieba\\dicts\\%s.txt
    stopWords: static/stopWords.out
  sign:
    split: /

